##########################################################
# FILE        : 470synth.tcl                             #
# Description : Synopsys Design Compiler Script for 470  #
# Usage       : dc_shell -tcl_mode -f mult.tcl           #
##########################################################

##########################
# ---- Introduction ---- #
##########################

# Welcome to the EECS 470 design compiler synthesis script!
# this will synthesize a module with predefined constraints using the synopsys design compiler
# and supports optional hierarchical synthesis or module parameters
# this is written in the Tool command language for Synopsys Design Compiler
# see the tcl_reference.tcl file for a general Tcl syntax reference
# it requires a number of environment variables as arguments, see below

# this script generates the following useful files: ("*" is the design name)
# stdout     - all commands here and their output
# *.vg       - the synthesized structural verilog module netlist
# *.chk      - the check file of warnings and errors in the design
#              many warnings are safely ignorable, don't stress about them
# *.rep      - area, timing, constraint, resource, and netlist reports
#              mainly used for checking slack: run 'grep slack *.rep' to view slack

# and these files that you can just ignore: (these are created automatically :/)
# cksum_dir
# command.log  - a list of *every* command run, but without their output
#                includes all setup commands so can be a good reference, but hides this file far below
# *.mr         - meant for use with VHDL, can ignore since we use SystemVerilog
# default.svf  - used for formal verification of the compiled functionality
# *.pvl        - generated by the analyze command, loaded by dc_shell to avoid recompiling
#                if your design doesn't seem to be updating, delete this file
# *.syn        - generated by the analyze command, you can ignore these

########################################
# ---- load environment variables ---- #
########################################

# this script requires the following environment variables:
# CLOCK_PERIOD - the clock period                                  (a float)
# SOURCES      - a list of verilog source files (no header files)  (a space-separated string)
# MODULE       - the name of the top level module from the sources (a string)

# this script supports hierarchical synthesis through these *optional* environment variables:
# CHILD_MODULES - modules that will be included as-is and not recompile (a space-separated string)
# DDC_FILES     - the ddc sources that contain these child modules      (a space-separated string)

# also this optional environment variable:
# DC_SHELL_MULTICORE - how many CPU cores to use when compiling (an integer)

#/***********************************************************/
#/* The following lines must be updated for every           */
#/* new design                                              */
#/***********************************************************/

try {
    set clock_period [getenv CLOCK_PERIOD]
    set SOURCES [getenv SOURCES]
    set design_name [getenv MODULE]
} on error {msg} {
    puts "ERROR: failed to load a required environment variable"
    puts "Message: $msg"
    exit 1
}

set netlist_file ${design_name}.vg       ;# our SystemVerilog file! it's generated here!
set rep_file     ${design_name}.rep      ;# check, area, timing, constraint, resource, and netlist reports

# how many CPU cores to use when compiling
# (this try block fails silently if the variable is missing)
try { set_host_options -max_cores [getenv DC_SHELL_MULTICORE] } on error {} {}

##########################################
# ---- link library and search path ---- #
##########################################


# these variables are needed by analyze and elaborate and by the 'link' command further down

set primary_corner lec25dscc25_TT
#set primary_corner saed32rvt_tt1p05v25c
#set primary_corner saed32rvt_ff1p16v25c

# these variables are needed by analyze and elaborate and by the 'link' command further down
set target_library [list ${primary_corner}.db ]
#set target_library [list saed32rvt_tt1p05v25c.db saed32hvt_tt1p05v25c.db saed32lvt_tt1p05v25c.db ]

# link_library is a variable for resolving standard cell references in designs
# the standard cell library we use is in the above .db file
# the * will have dc_shell search its own library first, then the target
set link_library "* $target_library"

# the search path is where dc_shell will search for files to read and load
# The PDK db files are located in the hardcoded paths below, specific to CAEN.
# If the tool reports these are missing, try `aklog` in your terminal.
set search_path [ list "./" "../" "/usr/caen/misc/class/eecs470/lib/synopsys/" \
  "/afs/umich.edu/class/eecs598-002/SAED32/SAED32_EDK/lib/stdcell_rvt/db_ccs/" \
  "/afs/umich.edu/class/eecs598-002/SAED32/SAED32_EDK/lib/stdcell_hvt/db_ccs/" \
  "/afs/umich.edu/class/eecs598-002/SAED32/SAED32_EDK/lib/stdcell_lvt/db_ccs/" \ 
]

###########################################
# ---- setup miscellaneous variables ---- #
###########################################

# this script assumes your clock and reset variables will be named "clock" and "reset" everywhere
# note: these are just local variables
set clock_name clock

# this makes it so you don't need to add
# // synopsys sync_set_reset "reset"
# before every always_ff block
set hdlin_ff_always_sync_set_reset "true"

# Set some flags to suppress warnings that are safe to ignore in 470
set suppress_errors "UID-401"

#############################################
# ---- read and elaborate source files ---- #
#############################################

# read files now so that we can fail quickly if analysis or elaboration have errors
# try to elaborate and set the current design, but quit early if there are errors
# the combination of analyze and elaborate does the same thing as read_file
# analyze doesn't accept header files but does allow expanding parameters
analyze -f sverilog $SOURCES
elaborate ${design_name}

#/***********************************************************/
#/* The rest of this file may be left alone for most small  */
#/* to moderate sized designs.  You may need to alter it    */
#/* when synthesizing your final project.                   */
#/***********************************************************/

if { [current_design $design_name] == [list] } {exit 1}

####################################
# ---- synthesize the design! ---- #
####################################

# Set some flags for optimization

set_app_var compile_top_all_paths "true"
set_app_var auto_wire_load_selection "false"

# link our current design against the link_library
# exit if there was an error
if { ![link] } {exit 1}

# Set wire load model
set_wire_load_model -name tsmcwire -lib lec25dscc25_TT $design_name
#set_wire_load_model -name "ForQA" -lib $primary_corner $design_name
set_wire_load_mode top
set_fix_multiple_port_nets -outputs -buffer_constants

# the driving cell from the link_library
set_driving_cell -lib_cell dffacs1 -pin Q [all_inputs]
#set_driving_cell -lib_cell DFFX1_RVT -pin Q [all_inputs]

# Generate clock
create_clock -period $clock_period -name $clock_name [find port $clock_name]
# the latency/transition time of the clock
set_clock_uncertainty 0.1 $clock_name
set_fix_hold $clock_name

group_path -from [get_ports "mem2proc_*"] -name mem2proc_grp
group_path -to [get_ports "proc2mem_*"] -name proc2mem_grp

# Set design constraints
#set_max_fanout 8 [current_design]
set_fanout_load 10 [all_outputs] ; avg
set_load 0.1 [all_outputs] ; avg
# set_max_transition 1.0 [current_design]
set_max_delay $clock_period [all_outputs]
set_max_delay $clock_period [all_registers]
set_critical_range 0.1 [current_design]
set_input_delay 0.1 -clock $clock_name [all_inputs]
set_output_delay 0.1 -clock $clock_name [all_outputs]
set_input_delay  [expr [expr {$clock_period / 2.0} + 2.5]] -clock $clock_name [get_ports "mem2proc*"]
set_output_delay [expr [expr {$clock_period / 2.0} + 2.0]] -clock $clock_name [get_ports "proc2mem_*a*d*"]
set_output_delay [expr [expr {$clock_period / 2.0} + 1.0]] -clock $clock_name [get_ports "proc2mem_data"]

# remove constraints for only the clock and reset
# Might or might not need these after the others
remove_driving_cell [find port $clock_name]
remove_input_delay -clock $clock_name [find port $clock_name]
remove_attribute [get_ports "reset"] max_fanout
#set_dont_touch $reset_name
set_resistance 0 $reset_name
set_drive 0 $reset_name

# Separate the subdesign instances to improve synthesis (excluding set_dont_touch designs)
# do this before writing the check file
uniquify
ungroup -all -flatten

# write the rep file before compiling
redirect $rep_file { check_design }

set_message_info -id {LINT-99} -severity "ignore"

# where the magic happens
# map_effort can be changed to high if you're ok with time increasing for better performance
# or you can change from compile to compile_ultra for best performance, but likely increased time
compile -map_effort high -area_effort none
# compile_ultra

################################
# ---- write output files ---- #
################################

# write the design back into SystemVerilog
write_file -hierarchy -format verilog -output $netlist_file $design_name

# write the design into both sv and ddc formats, also the svsim wrapper
write_file -hierarchy -format verilog -output $netlist_file $design_name
write_file -hierarchy -format ddc     -output $ddc_file     $design_name
write_file            -format svsim   -output $svsim_file   $design_name

# note the check has already been written
# the various reports (design, area, timing, constraints, resources)
redirect -append $rep_file { report_design -nosplit }
redirect -append $rep_file { report_timing -max_paths 2 -input_pins -nets -transition_time -nosplit }
redirect -append $rep_file { report_constraints -all_violators -verbose -nosplit -significant_digits 4 }
redirect -append $rep_file { report_power }
redirect -append $rep_file { report_resources -hier }
redirect -append $rep_file { report_area -hierarchy }

# also report a reference of the used modules from the final netlist
remove_design -all
read_file -format verilog $netlist_file
current_design $design_name
redirect -append $rep_file { report_reference -nosplit -hierarchy }

exit 0 ;# success! (maybe)